"""Renders an approved invoice as a downloadable PDF — the actual document
the admin sends to a client, not just a screen. Pure-python (fpdf2), no
system dependencies, so it works the same locally and on Streamlit Cloud.

The core Helvetica font fpdf2 ships with is latin-1 only, so amounts use
"NGN" here instead of the ₦ glyph the rest of the app displays — that's a
PDF-rendering detail, not a change to how amounts are shown on screen.
"""

from __future__ import annotations

from fpdf import FPDF

NAVY = (10, 37, 64)
TEAL = (26, 188, 156)
GREY = (138, 148, 166)


def _money(amount: float) -> str:
    return f"NGN {amount:,.2f}"


_REPLACEMENTS = {
    "—": "-", "–": "-", "‘": "'", "’": "'",
    "“": '"', "”": '"', "…": "...", "₦": "NGN ",
}


def _safe(text: str | None) -> str:
    """The core Helvetica font is latin-1 only; job titles/descriptions are
    free text and can contain an em-dash, curly quote, or the Naira sign —
    swap the common ones for a plain equivalent and drop anything else that
    still doesn't fit, rather than letting a PDF download crash on it."""
    if not text:
        return ""
    for bad, good in _REPLACEMENTS.items():
        text = text.replace(bad, good)
    return text.encode("latin-1", "replace").decode("latin-1")


def build_invoice_pdf(invoice: dict, lines: list, total: float) -> bytes:
    pdf = FPDF(unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 12, "RABBI CONSULT", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 6, "Corporate, Immigration, Tax & State Matters", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 10, _safe(invoice["invoice_code"]), new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*GREY)
    status_label = {
        "pending_approval": "Pending approval", "approved": "Approved",
        "paid": "Paid", "rejected": "Rejected",
    }.get(invoice["status"], invoice["status"].title())
    pdf.cell(0, 6, f"Status: {status_label}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    col_x = pdf.get_x()
    col_y = pdf.get_y()
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*NAVY)
    pdf.cell(90, 6, "Bill to", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(90, 6, _safe(invoice["client_name"]), new_x="LMARGIN", new_y="NEXT")
    if invoice.get("client_contact_name"):
        pdf.cell(90, 6, _safe(invoice["client_contact_name"]), new_x="LMARGIN", new_y="NEXT")
    if invoice.get("client_contact_email"):
        pdf.cell(90, 6, _safe(invoice["client_contact_email"]), new_x="LMARGIN", new_y="NEXT")

    pdf.set_xy(col_x + 100, col_y)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(90, 6, "Invoice details", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(col_x + 100)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(90, 6, f"Date: {invoice['invoice_date'].isoformat()}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(col_x + 100)
    pdf.cell(90, 6, _safe(f"Submitted by: {invoice.get('created_by_name') or '-'}"), new_x="LMARGIN", new_y="NEXT")
    if invoice.get("approved_by_name"):
        pdf.set_x(col_x + 100)
        pdf.cell(90, 6, _safe(f"Approved by: {invoice['approved_by_name']}"), new_x="LMARGIN", new_y="NEXT")
    if invoice.get("payment_reference"):
        pdf.set_x(col_x + 100)
        pdf.cell(90, 6, _safe(f"Payment ref: {invoice['payment_reference']}"), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)

    pdf.set_fill_color(*NAVY)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(110, 8, "  Description", fill=True)
    pdf.cell(40, 8, "Job", fill=True)
    pdf.cell(40, 8, "Amount", fill=True, align="R", new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(*NAVY)
    pdf.set_font("Helvetica", "", 10)
    fill = False
    for line in lines:
        pdf.set_fill_color(247, 249, 250) if fill else pdf.set_fill_color(255, 255, 255)
        pdf.cell(110, 8, _safe(f"  {line['description']}"), fill=True)
        pdf.cell(40, 8, _safe(line["job_code"]), fill=True)
        pdf.cell(40, 8, _money(float(line["amount"])) + "  ", fill=True, align="R", new_x="LMARGIN", new_y="NEXT")
        fill = not fill

    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(150, 8, "Total", align="R")
    pdf.cell(40, 8, _money(total), align="R", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(14)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 5, "Rabbi Consult - generated by Rabbi Core", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())
